--Natural Join


SELECT AVAILABLE FROM TOUR_GUIDE NATURAL JOIN PACKAGE;

SELECT DESTINATION FROM PACKAGE NATURAL JOIN TOUR_ORDER;


--Self Join


INSERT INTO PACKAGE( PACKAGE_ID, TOUR_GUIDE_ID, PERSONS, DESTINATION, PRICE, EXPIRE_DATE) VALUES ( 20210, 004, 5, 'HIMACHAL PRADES', 800.00, '03-MAR-23');

INSERT INTO TOUR_ORDER( TOUR_ORDER_ID, CUSTOMER_ID, PACKAGE_ID, TOUR_GUIDE_ID, DATE_) VALUES ( 202210, '07', 20210, 002, '29-AUG-22');


SELECT CUSTOMER_ID FROM TOUR_ORDER AS T1, TOUR_ORDER AS T2 WHERE T1.CUSTOMER_ID = T2.CUSTOMER_ID AND T1.PACKAGE_ID < > T2.PACKAGE_ID;


--Equi Join


SELECT NAME FROM TOUR_GUIDE JOIN PACKAGE ON TOUR_GUIDE.TOUR_GUIDE_ID = PACKAGE.TOUR_GUIDE_ID AND TOUR_GUIDE.TOUR_AREA = PACKAGE.DESTINATION;



--Left Outer Join


SELECT NAME, ADDRESS, PHONE_NO FROM TOUR_GUIDE LEFT OUTER JOIN PACKAGE ON TOUR_GUIDE.TOUR_GUIDE_ID = PACKAGE.TOUR_GUIDE_ID;

SELECT CUSTOMER_ID, PACKAGE_ID FROM TOUR_ORDER LEFT OUTER JOIN TOUR_GUIDE ON TOUR_ORDER.TOUR_GUIDE_ID = TOUR_GUIDE.TOUR_GUIDE_ID;


--Right Outer join

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, ADDRESS, PHONE_NO) VALUES ( '10', 'MILI', 'MIRPUR 6', '01389064566');

SELECT NAME, ADDRESS, DATE_ FROM TOUR_ORDER RIGHT OUTER JOIN CUSTOMER ON TOUR_ORDER.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID;


SELECT DESTINATION, PRICE, DATE_ FROM TOUR_ORDER RIGHT OUTER JOIN PACKAGE ON TOUR_ORDER.PACKAGE_ID = PACKAGE.PACKAGE_ID;



--Full Outer Join

SELECT NAME, SALARY, DATE_ FROM TOUR_GUIDE FULL OUTER JOIN TOUR_ORDER ON TOUR_GUIDE.TOUR_GUIDE_ID = TOUR_ORDER.TOUR_GUIDE_ID;


SELECT NAME FROM TOUR_ORDER FULL OUTER JOIN CUSTOMER ON TOUR_ORDER.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID;



