SELECT * FROM CUSTOMER WHERE PHONE_NO LIKE '017%' AND NAME LIKE '%A';


SELECT COUNT(SALARY) FROM TOUR_GUIDE WHERE SALARY >= 15000 AND SALARY <= 18000;


SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 06;


SELECT DESTINATION FROM PACKAGE WHERE PRICE = 600.00;


SELECT MIN(SALARY) AS MINIMUM_SALARY FROM TOUR_GUIDE;


SELECT PHONE_NO FROM CUSTOMER WHERE NAME LIKE 'L%';