drop table tour_order;
drop table package;
drop table tour_guide;
drop table customer;

CREATE TABLE CUSTOMER ( CUSTOMER_ID VARCHAR(3), NAME VARCHAR(20), ADDRESS VARCHAR(30), PHONE_NO VARCHAR(44), PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE TOUR_GUIDE ( TOUR_GUIDE_ID INTEGER, NAME VARCHAR(33), ADDRESS VARCHAR(43), PHONE_NO VARCHAR(36), SALARY INTEGER, AVAILABLE VARCHAR(3), TOUR_AREA VARCHAR(13), PRIMARY KEY(TOUR_GUIDE_ID)
);

CREATE TABLE PACKAGE ( PACKAGE_ID INTEGER, TOUR_GUIDE_ID INTEGER, PERSONS INTEGER, DESTINATION VARCHAR(48), PRICE DECIMAL(5,2), EXPIRE_DATE DATE, PRIMARY KEY(PACKAGE_ID), 
FOREIGN KEY (TOUR_GUIDE_ID) REFERENCES TOUR_GUIDE(TOUR_GUIDE_ID)
);

CREATE TABLE TOUR_ORDER ( TOUR_ORDER_ID INTEGER, CUSTOMER_ID VARCHAR(3), PACKAGE_ID INTEGER, TOUR_GUIDE_ID INTEGER, DATE_ DATE, PRIMARY KEY(TOUR_ORDER_ID), 
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID), FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGE (PACKAGE_ID), FOREIGN KEY (TOUR_GUIDE_ID) REFERENCES TOUR_GUIDE (TOUR_GUIDE_ID)
);
